#
# arch/arm/mach-tegra/microsoft-surface-rt/Makefile
#
# Copyright (c) 2010-2011, NVIDIA Corporation.
#
# This software is licensed under the terms of the GNU General Public
# License version 2, as published by the Free Software Foundation, and
# may be copied, distributed, and modified under those terms.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
#

obj-${CONFIG_MACH_SURFACE_RT} 		+= board-surface-rt.o
obj-${CONFIG_MACH_SURFACE_RT} 		+= board-surface-rt-kbc.o
obj-${CONFIG_MACH_SURFACE_RT} 		+= board-surface-rt-memory.o
obj-${CONFIG_MACH_SURFACE_RT} 		+= board-surface-rt-panel.o
obj-${CONFIG_MACH_SURFACE_RT} 		+= board-surface-rt-pinmux.o
obj-${CONFIG_MACH_SURFACE_RT} 		+= board-surface-rt-power.o
obj-${CONFIG_MACH_SURFACE_RT} 		+= board-surface-rt-sdhci.o
obj-${CONFIG_MACH_SURFACE_RT} 		+= board-surface-rt-sensors.o
obj-${CONFIG_MACH_SURFACE_RT} 		+= board-surface-rt-i2c-hid.o
